# Generated by Django 5.2.4 on 2025-08-10 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_alter_comment_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='text',
        ),
    ]
